require('maps')
require('plugins')
require('_autopairs')
require('_ts-autotag')
require('_lspconfig')
require('_lualine')
require('_lspkind')
require('_telescope')
require('_nvim-tree')
require('_catppuccin')
require('_indent-blankline')
require('_noice')
require('_cmp')
require('_lspsaga')
require('_comment')
require('_zen-mode')

