return {
  -- {
  --   "telescope.nvim",
  --   lazy = true,
  --   event = "VimEnter",
  --   dependencies = {
  --     {
  --       "nvim-telescope/telescope-fzf-native.nvim",
  --       build = "make",
  --     },
  --     "nvim-telescope/telescope-file-browser.nvim",
  --   },
  --   keys = {
  --     {
  --       "<leader>f\\",
  --       function()
  --         local builtin = require("telescope.builtin")
  --         builtin.buffers()
  --       end,
  --       desc = "Lists open buffers",
  --     },
  --     {
  --       "<leader>fb",
  --       function()
  --         local telescope = require("telescope")
  --
  --         local function telescope_buffer_dir()
  --           return vim.fn.expand("%:p:h")
  --         end
  --
  --         telescope.extensions.file_browser.file_browser({
  --           path = "%:p:h",
  --           cwd = telescope_buffer_dir(),
  --           respect_gitignore = false,
  --           hidden = true,
  --           grouped = true,
  --           previewer = true,
  --         })
  --       end,
  --       desc = "Open File Browser with the path of the current buffer",
  --     },
  --   },
  --   config = function(_, opts)
  --     local telescope = require("telescope")
  --     local actions = require("telescope.actions")
  --     local fb_actions = require("telescope").extensions.file_browser.actions
  --
  --     opts.defaults = vim.tbl_deep_extend("force", opts.defaults, {
  --       -- theme = "ivy",
  --       initial_mode = "normal",
  --       wrap_results = true,
  --       include_declaration = false,
  --       layout_strategy = "horizontal",
  --       layout_config = { prompt_position = "top" },
  --       sorting_strategy = "ascending",
  --       winblend = 0,
  --     })
  --
  --     opts.pickers = {
  --       diagnostics = {
  --         layout_config = {
  --           preview_cutoff = 9999,
  --         },
  --       },
  --     }
  --
  --     opts.extensions = {
  --       file_browser = {
  --         hidden = true,
  --         -- disables netrw and use telescope-file-browser in its place
  --         hijack_netrw = true,
  --         previewer = true,
  --         respect_gitignore = false,
  --         grouped = true,
  --         mappings = {
  --           -- your custom insert mode mappings
  --           ["n"] = {
  --             -- your custom normal mode mappings
  --             ["R"] = fb_actions.rename,
  --             ["M"] = fb_actions.move,
  --             ["N"] = fb_actions.create,
  --             ["D"] = fb_actions.remove,
  --             ["h"] = fb_actions.goto_parent_dir,
  --             ["/"] = function()
  --               vim.cmd("startinsert")
  --             end,
  --             ["<C-u>"] = function(prompt_bufnr)
  --               for _ = 1, 10 do
  --                 actions.move_selection_previous(prompt_bufnr)
  --               end
  --             end,
  --             ["<C-d>"] = function(prompt_bufnr)
  --               for _ = 1, 10 do
  --                 actions.move_selection_next(prompt_bufnr)
  --               end
  --             end,
  --             ["<C-t>"] = function(bufnr)
  --               actions.select_tab(bufnr)
  --             end,
  --             ["<PageUp>"] = actions.preview_scrolling_up,
  --             ["<PageDown>"] = actions.preview_scrolling_down,
  --           },
  --         },
  --       },
  --     }
  --     telescope.setup(opts)
  --     require("telescope").load_extension("fzf")
  --     require("telescope").load_extension("file_browser")
  --   end,
  -- },
  {
    "tiagovla/scope.nvim",
    config = function()
      require("scope").setup({})
    end,
  },
  -- {
  --   { "LintaoAmons/cd-project.nvim" },
  -- },
  -- lazy.nvim
}
